# Generated by Django 5.2.17 on 2026-10-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                ("skill_id", models.AutoField(primary_key=True, serialize=False)),
                ("skill_name", models.CharField(max_length=100, unique=True)),
                ("category", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "skills",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserSkill",
            fields=[
                ("user_skill_id", models.AutoField(primary_key=True, serialize=False)),
                ("skill_level", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "years_experience",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("is_verified", models.IntegerField(blank=True, null=True)),
                ("added_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "user_skills",
                "managed": False,
            },
        ),
    ]
