# Generated by Django 5.2.17 on 2026-10-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobRole",
            fields=[
                ("role_id", models.AutoField(primary_key=True, serialize=False)),
                ("role_name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "experience_level",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "job_roles",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="JobRoleSkill",
            fields=[
                ("role_skill_id", models.AutoField(primary_key=True, serialize=False)),
                ("importance", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "minimum_level",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
            ],
            options={
                "db_table": "job_role_skills",
                "managed": False,
            },
        ),
    ]
