# Generated by Django 5.2.17 on 2026-10-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LearningProgress",
            fields=[
                ("progress_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "progress_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("status", models.CharField(blank=True, max_length=30, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "learning_progress",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LearningResource",
            fields=[
                ("resource_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "resource_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "resource_url",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("difficulty", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "estimated_hours",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "learning_resources",
                "managed": False,
            },
        ),
    ]
